### ISSUE TITLE
Unable to import Sequence from collections during docker build

### ISSUE THREAD

**Issue by kaumaron** [docker/getting-started#206]
Error running `docker build -t docker101tutorial .`

I'm seeing this error during the YARN tests. I'm not sure where the python call for collections.Sequence is coming from.

```=> ERROR [build 2/2] RUN mkdocs build                   0.4s
------                                                        
 > [build 2/2] RUN mkdocs build:
#23 0.379 Traceback (most recent call last):
#23 0.379   File "/usr/local/bin/mkdocs", line 5, in <module>
#23 0.379     from mkdocs.__main__ import cli
#23 0.379   File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 14, in <module>
#23 0.379     from mkdocs import config
#23 0.379   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/__init__.py", line 2, in <module>
#23 0.379     from mkdocs.config.defaults import DEFAULT_SCHEMA
#23 0.379   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 4, in <module>
#23 0.379     from mkdocs.config import config_options
#23 0.379   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 5, in <module>
#23 0.380     from collections import Sequence, namedtuple
#23 0.380 ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
------
executor failed running [/bin/sh -c mkdocs build]: exit code: 1```

**Comment by kaumaron** [comment]
> See this: [25f25d8](https://github.com/docker/getting-started/commit/25f25d812644a6ed20778ffc1ab00e2ae0943ac9)

Thanks
