### ISSUE TITLE
Can't find Python executable "python"

### ISSUE THREAD

**Issue by visuallization** [docker/getting-started#227]
Hi folks,

I am having troubles getting your basic "getting started" tutorial (https://docs.docker.com/get-started/02_our_app/) to work on my apple m1 macbook.

Once I created the Dockerfile as recommended in the app directory:

```
FROM node:12-alpine
# Adding build tools to make yarn install work on Apple silicon / arm64 machines
RUN apk add --no-cache python3 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
```

And I run:

`https://docs.docker.com/get-started/02_our_app/`

I get the following error in Step [5/5] while the docker build process is yarning.

```
 > [5/5] RUN yarn install --production:
#9 0.255 yarn install v1.22.15
#9 0.302 [1/4] Resolving packages...
#9 0.516 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#9 0.518 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#9 0.696 warning sqlite3 > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
#9 0.726 warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#9 0.781 warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
#9 0.861 warning sqlite3 > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#9 1.115 [2/4] Fetching packages...
#9 6.561 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#9 6.561 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#9 6.569 [3/4] Linking dependencies...
#9 6.988 [4/4] Building fresh packages...
#9 7.884 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#9 7.884 error /app/node_modules/sqlite3: Command failed.
#9 7.884 Exit code: 1
#9 7.884 Command: node-pre-gyp install --fallback-to-build
#9 7.884 Arguments:
#9 7.884 Directory: /app/node_modules/sqlite3
#9 7.884 Output:
#9 7.884 node-pre-gyp info it worked if it ends with ok
#9 7.884 node-pre-gyp info using node-pre-gyp@0.11.0
#9 7.884 node-pre-gyp info using node@12.22.7 | linux | arm64
#9 7.884 node-pre-gyp WARN Using request for node-pre-gyp https download
#9 7.884 node-pre-gyp info check checked for "/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
#9 7.884 node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#9 7.884 node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#9 7.884 node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#9 7.884 node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@12.22.7 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
#9 7.884 node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#9 7.884 gyp info it worked if it ends with ok
#9 7.884 gyp info using node-gyp@3.8.0
#9 7.884 gyp info using node@12.22.7 | linux | arm64
#9 7.884 gyp info ok
#9 7.884 gyp info it worked if it ends with ok
#9 7.884 gyp info using node-gyp@3.8.0
#9 7.884 gyp info using node@12.22.7 | linux | arm64
#9 7.884 gyp ERR! configure error
#9 7.884 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#9 7.884 gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#9 7.884 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#9 7.884 gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#9 7.884 gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#9 7.884 gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#9 7.884 gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#9 7.884 gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#9 7.884 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
#9 7.884 gyp ERR! System Linux 5.10.25-linuxkit
#9 7.884 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#9 7.884 gyp ERR! cwd /app/node_modules/sqlite3
#9 7.884 gyp ERR! node -v v12.22.7
#9 7.884 gyp ERR! node-gyp -v v3.8.0
#9 7.884 gyp ERR! not ok
#9 7.884 node-pre-gyp ERR! build error
#9 7.884 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#9 7.884 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#9 7.884 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#9 7.884 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#9 7.884 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#9 7.884 node-pre-gyp ERR! System Linux 5.10.25-linuxkit
#9 7.884 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#9 7.884 node-pre-gyp ERR! cwd /app/node_modules/sqlite3
#9 7.884 node-pre-gyp ERR! node -v v12.22.7
#9 7.884 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#9 7.884 node-pre-gyp ERR! not ok
#9 7.884 Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1
```

Basically it seems that it has troubles finding python even though I see you added this line in the Dockerfile a few weeks ago:
`RUN apk add --no-cache python3 g++ make`

Any help would be appreciated.

Cheers,
Florentin

**Comment by visuallization** [comment]
The workaround to install python2 mentioned here: https://github.com/docker/getting-started/issues/222#issuecomment-978730011 worked for me! But I still think still should be fixed.

**Comment by ColemanDunn** [comment]
Slightly clearer solution [here](https://github.com/docker/getting-started/issues/231#issuecomment-1018641262)

[Slightly more context](https://github.com/docker/getting-started/issues/231#issuecomment-1110175000)

**Comment by exerror8** [comment]
[[Solved] Can’t find Python executable “python”, you can set the PYTHON env variable](https://exerror.com/cant-find-python-executable-python-you-can-set-the-python-env-variable/)

**Comment by mikesir87** [comment]
Hi all! 👋  Thanks for opening an issue and apologies for the delay in getting back to you. We recognize this issue is fairly old, so you all have most likely moved on a long time ago. Both our guide and Docker Desktop have improved a lot since then, many of which changes have hopefully resolved the issue you were experiencing. Therefore, we're going to go ahead and close out this issue. 

If you're still having issues, feel free to create a new issue and we can help you out going forward.
