### ISSUE TITLE
docker build -t docker101tutorial . causes ERROR [build 2/2] RUN mkdocs build

### ISSUE THREAD

**Issue by lawrencefrias** [docker/getting-started#257]
Running the tutorial to build the image in docker on Windows 11 results in the following error:

=> ERROR [build 2/2] RUN mkdocs build                                                                                                                0.6s
------
 > [build 2/2] RUN mkdocs build:
#23 0.525 Traceback (most recent call last):
#23 0.525   File "/usr/local/bin/mkdocs", line 8, in <module>
#23 0.525     sys.exit(cli())
#23 0.525   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
#23 0.525     return self.main(*args, **kwargs)
#23 0.525   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
#23 0.526     rv = self.invoke(ctx)
#23 0.526   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
#23 0.526     return _process_result(sub_ctx.command.invoke(sub_ctx))
#23 0.526   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
#23 0.526     return ctx.invoke(self.callback, **ctx.params)
#23 0.526   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
#23 0.527     return __callback(*args, **kwargs)
#23 0.527   File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 187, in build_command
#23 0.527     build.build(config.load_config(**kwargs), dirty=not clean)
#23 0.527   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 216, in load_config
#23 0.527     from mkdocs.config.defaults import get_schema
#23 0.527   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 1, in <module>
#23 0.528     from mkdocs.config import config_options
#23 0.528   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 8, in <module>
#23 0.528     from mkdocs import utils, theme, plugins
#23 0.528   File "/usr/local/lib/python3.10/site-packages/mkdocs/theme.py", line 6, in <module>
#23 0.528     from mkdocs.utils import filters
#23 0.528   File "/usr/local/lib/python3.10/site-packages/mkdocs/utils/filters.py", line 13, in <module>
#23 0.529     @jinja2.contextfilter
#23 0.529 AttributeError: module 'jinja2' has no attribute 'contextfilter'
------
executor failed running [/bin/sh -c mkdocs build]: exit code: 1

I've tried various things like changing jinja2 and mkdocs versions but nothing seems to be working.

**Comment by dglaserg** [comment]
I got the same issue. From the [Jinja2 change logs](https://jinja.palletsprojects.com/en/3.1.x/changes/) version 3.1.0 states:

> `contextfilter` and `contextfunction` are replaced by `pass_context`. `evalcontextfilter` and `evalcontextfunction` are replaced by `pass_eval_context`. `environmentfilter` and `environmentfunction` are replaced by `pass_environment`.

This is a Jinja2 and mkdocs issue and a good example of why you want to have all your dependency versions set in `requirements.txt`.

I added `jinja2==3.0.3` at the very beginning of `requirements.txt` and it worked for me.

**Comment by JohnLukeBentley** [comment]
I had the same problem. With thanks @dglaserg's fix also worked for me.

Docker Desktop 4.6.1 (76265) 

Edition	Windows 10 Pro
Version	21H1
Installed on	‎2020-‎05-‎31, ‎Sun
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by goose000** [comment]
Same problem, fix also worked.
Created pull request to fix: https://github.com/docker/getting-started/pull/259

**Comment by lawrencefrias** [comment]
@dglaserg thanks your workaround worked brilliantly. I actually had tried that before but I did not have the jinja2 version set on the first line of requirements.txt

For reference, here's what my file looks like now in case others are having the same issue:

jinja2==3.0.3
mkdocs==1.2.3
mkdocs-material==4.6.3
mkdocs-minify-plugin==0.2.3
pygments==2.7.4
pymdown-extensions==7.0

**Comment by rockyoung** [comment]
> I got the same issue. From the [Jinja2 change logs](https://jinja.palletsprojects.com/en/3.1.x/changes/) version 3.1.0 states:
> 
> > `contextfilter` and `contextfunction` are replaced by `pass_context`. `evalcontextfilter` and `evalcontextfunction` are replaced by `pass_eval_context`. `environmentfilter` and `environmentfunction` are replaced by `pass_environment`.
> 
> This is a Jinja2 and mkdocs issue and a good example of why you want to have all your dependency versions set in `requirements.txt`.
> 
> I added `jinja2==3.0.3` at the very beginning of `requirements.txt` and it worked for me.

after adding `jinja2==3.0.3` at the top of `requirements.txt`, still get error when docker build:
> ERROR: Cannot install mkdocs because these package versions have conflicting dependencies.
#24 295.6
#24 295.6 The conflict is caused by:
#24 295.6     importlib-metadata 4.11.3 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.11.2 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.11.1 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.11.0 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.10.1 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.10.0 depends on zipp>=0.5  
#24 295.6     importlib-metadata 4.9.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.8.3 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.8.2 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.8.1 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.7.1 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.6.4 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.6.3 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.6.2 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.6.1 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.6.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.5.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.4.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.3.1 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.3.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.2.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.1.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.0.1 depends on zipp>=0.5   
#24 295.6     importlib-metadata 4.0.0 depends on zipp>=0.5   
#24 295.6     importlib-metadata 3.10.1 depends on zipp>=0.5  
#24 295.6     importlib-metadata 3.10.0 depends on zipp>=0.5  
#24 295.6
#24 295.6 To fix this you could try to:
#24 295.6 1. loosen the range of package versions you've specified
#24 295.6 2. remove package versions to allow pip attempt to solve the dependency conflict
#24 295.6
#24 295.6 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
executor failed running [/bin/sh -c pip install -r requirements.txt]: exit code: 1

what should i do now?

**Comment by spykard** [comment]
I think there is an even simpler fix, instead of adding the jinja2 line in `requirements.txt`, updating mkdocs to 1.3.0 works for me. 
As a result change `requirements.txt` to: 
`mkdocs==1.3.0`

**Comment by kumar6808** [comment]
I was facing the same issue and the @spykard fix also works.

**Comment by CarlSargunar** [comment]
Thanks for this - @spykard - that fix also worked for me

I did get a couple of timeout errors when trying to build the image locally, but trying again just solved that. 

For reference, I build locally using the following

`docker build --tag=getting-started .`

**Comment by StefanScherer** [comment]
PR #265 got merged. I'll push a new docker/getting-started image soon.
