### ISSUE TITLE
I'm trying to run a docker image but I keep having the error below.

### ISSUE THREAD

**Issue by nacerkraa** [docker/getting-started#343]
docker run -p 8080:8080 nacer/my-image-name-1
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by mikesir87** [comment]
Hi there and thanks for opening an issue in the repo. This repo is specifically focused on the Getting Started guide/tutorial shipped with Docker and not for general troubleshooting. Therefore, I'm going to close the issue. 

But, you are welcome to love the conversation to our Forums, community Slack, Reddit, or Twitter to get additional help.

Despite that, it looks like you might be trying to run a Java app using a version of the JRE that doesn't support the version the app was compiled against. I'd look up the specific error to see what version of Java you need to use and then update your image base with that version.
