### ISSUE TITLE
getting-started app container stops immediately

### ISSUE THREAD

**Issue by liquidkey** [docker/getting-started#87]
Hi, 

I am learning docker by following the tutorial in docker/getting-started image. I following the steps as mentioned but when I run my image container it stops with the following logs. I am posting output of the command here

```
> docker build -t getting-started .
Sending build context to Docker daemon  4.659MB
Step 1/5 : FROM node:12-alpine
 ---> 1f52b7199ba6
Step 2/5 : WORKDIR /app
 ---> Using cache
 ---> dfd91d5abf63
Step 3/5 : COPY . .
 ---> e35813c807c6
Step 4/5 : RUN yarn --install production
 ---> Running in 11960781a554
yarn run v1.22.4
error There are no binary scripts available.
info Project commands
   - dev
      nodemon src/index.js
   - prettify
      prettier -l --write "**/*.js"
   - test
      jest
error No command specified.
Done in 0.02s.
Removing intermediate container 11960781a554
 ---> 9e7b69c3ebe8
Step 5/5 : CMD [ "node", "src/index.js" ]
 ---> Running in 575b099c1f56
Removing intermediate container 575b099c1f56
 ---> 8c9b9efe1096
Successfully built 8c9b9efe1096
Successfully tagged getting-started:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

```
```
> docker run -dp 3000:3000 getting-started
internal/modules/cjs/loader.js:968

throw err;
^
Error: Cannot find module 'express'
Require stack:

- /app/src/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/app/src/index.js:1:17)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/src/index.js' ]
}
```

**Comment by liquidkey** [comment]
Oops! I reviewed the Dockerfile again and found a error in the yarn command. fixing that solved the issue. I was running 
`yarn --install production` instead of `yarn install --production`
